# Generated by Django 4.1.7 on 2023-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='size2',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('XXXXL', 'XXXXL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
