# Generated by Django 4.1.7 on 2023-09-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_cloth_color_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='image',
        ),
    ]
